# Generated by Django 5.0.1 on 2024-02-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_layouts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
