# Generated by Django 5.0.1 on 2024-02-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_layouts', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
