# Generated by Django 5.0.2 on 2024-03-15 10:44

import app_layouts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_layouts', '0004_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_category', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_layouts.models.getFileName)),
                ('description', models.TextField(blank=True, max_length=750, null=True)),
                ('status', models.BooleanField(default=False, help_text='0-show status || 1- hidden')),
                ('emergant_lancer', models.BooleanField(default=True, help_text='0-show status || 1- hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=150)),
                ('about_me', models.TextField(max_length=1000)),
                ('address_1', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('adhar_number', models.IntegerField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('adhar_image', models.ImageField(upload_to=app_layouts.models.getFileName)),
                ('phone_number', models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_layouts.models.getFileName)),
                ('description', models.TextField(blank=True, max_length=750, null=True)),
                ('status', models.BooleanField(default=False, help_text='0-show status || 1- hidden')),
                ('Availabe_any_time', models.BooleanField(default=True, help_text='0-show status || 1- hidden')),
                ('emergant_lancer', models.BooleanField(default=True, help_text='0-show status || 1- hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_layouts.profession')),
            ],
        ),
    ]
