# Generated by Django 5.0.2 on 2024-03-23 12:15

import app_layouts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_layouts', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profession_category', models.CharField(max_length=150)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=app_layouts.models.getFileName)),
                ('Description', models.TextField(blank=True, max_length=750, null=True)),
                ('Status', models.BooleanField(default=False, help_text='0-show status || 1- hidden')),
                ('Emergant_freelancer', models.BooleanField(default=True, help_text='0-show status || 1- hidden')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='professionals',
            name='profession',
        ),
        migrations.CreateModel(
            name='professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=app_layouts.models.getFileName)),
                ('My_Profession', models.CharField(max_length=150)),
                ('About_me', models.CharField(max_length=1000)),
                ('Qualification', models.CharField(max_length=1000)),
                ('Skills', models.CharField(max_length=1000)),
                ('Experiance', models.TextField(blank=True, max_length=750, null=True)),
                ('Address_1', models.CharField(max_length=150)),
                ('Address_2', models.CharField(max_length=150)),
                ('District', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=150)),
                ('Country', models.CharField(max_length=150)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=128)),
                ('Age', models.IntegerField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Payment', models.PositiveIntegerField(max_length=5,null=False,blank=False)),
                ('Adhar_number', models.IntegerField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('Adhar_image', models.ImageField(upload_to=app_layouts.models.getFileName)),
                ('Phone_number', models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('WhatsApp_number', models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('Email', models.EmailField(null=False,blank=False)),
                ('Linkedin', models.URLField(max_length=150,null=True,blank=True)),
                ('Status', models.BooleanField(default=False, help_text='0-show status || 1- hidden')),
                ('Availabe_any_time', models.BooleanField(default=True, help_text='0-show status || 1- hidden')),
                ('Emergant_freelancer', models.BooleanField(default=True, help_text='0-show status || 1- hidden')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_layouts.professions')),
            ],
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='professionals',
        ),
    ]
