# Generated by Django 5.0.2 on 2024-03-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_layouts', '0006_professions_remove_professionals_profession_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professions',
            new_name='Profession',
        ),
        migrations.RenameModel(
            old_name='professional',
            new_name='professionals',
        ),
    ]
