# Generated by Django 5.0.2 on 2024-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_layouts', '0007_rename_professions_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='Availabe_any_time',
            field=models.BooleanField(default=True, help_text='If Available Click Checkbox'),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='Emergant_freelancer',
            field=models.BooleanField(default=True, help_text='If You Are A Emergent Worker Click Checkbox'),
        ),
    ]
