# Generated by Django 5.0.2 on 2024-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_layouts', '0008_alter_professionals_availabe_any_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='About_me',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='Adhar_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='Age',
            field=models.PositiveIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='Phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='WhatsApp_number',
            field=models.CharField(max_length=10),
        ),
    ]
